Repository Azure/Azure-Proactive-Resiliency-Library, pull requests merged in 2023-12, with the labels that each got.

#149 Bug - Add missing firewall categories and fix rt-2 link
  .github/actions-config/mlc_config.json
  docs/content/services/networking/firewall/_index.md
  docs/content/services/networking/route-table/_index.md
Labels: bug

#157 Adds GitHub policies for managing contributions.
  .github/policies/resource-managment.yml
Labels: enhancement

#154 lb-1 query fixed
  docs/content/services/networking/load-balancer/_index.md
  docs/content/services/networking/load-balancer/code/lb-1/lb-1.kql
  docs/content/services/networking/load-balancer/code/lb-1/lb-1.kql.fix
Labels: Bug, Area: Resource Graph Query(s)

#158 APRL WAF updates to fix merge conflict from Oct 2023
  docs/content/services/networking/web-application-firewall/_index.md
  docs/content/services/networking/web-application-firewall/code/waf-1/waf-1.kql
  docs/content/services/networking/web-application-firewall/code/waf-2/waf-2.kql
  docs/content/services/networking/web-application-firewall/code/waf-3/waf-3.kql
  docs/content/services/networking/web-application-firewall/code/waf-4/waf-4.kql
  docs/content/services/networking/web-application-firewall/code/waf-6/waf-6.kql
  docs/content/services/networking/web-application-firewall/code/waf-7/waf-7.kql
  docs/content/services/networking/web-application-firewall/code/waf-8/waf-8.kql
Labels: Bug, Area: Service Guidance, Area: Resource Graph Query(s)

#159 APRL ERG updates to fix merge conflicts from Oct 2023
  docs/content/services/networking/expressroute-gateway/_index.md
  docs/content/services/networking/expressroute-gateway/code/erg-1/erg-1.kql
  docs/content/services/networking/expressroute-gateway/code/erg-3/erg-3.kql
Labels: Bug, Area: Resource Graph Query(s)

#161 Adding Tags to VM Queries in APRL
  docs/content/services/compute/virtual-machines/code/vm-10/vm-10.kql
  docs/content/services/compute/virtual-machines/code/vm-11/vm-11.kql
  docs/content/services/compute/virtual-machines/code/vm-12/vm-12.kql
  docs/content/services/compute/virtual-machines/code/vm-14/vm-14.kql
  docs/content/services/compute/virtual-machines/code/vm-15/vm-15.kql
  docs/content/services/compute/virtual-machines/code/vm-16/vm-16.kql
  docs/content/services/compute/virtual-machines/code/vm-17/vm-17.kql
  docs/content/services/compute/virtual-machines/code/vm-18/vm-18.kql
  docs/content/services/compute/virtual-machines/code/vm-19/vm-19.kql
  docs/content/services/compute/virtual-machines/code/vm-2/vm-2.kql
  docs/content/services/compute/virtual-machines/code/vm-20/vm-20.kql
  docs/content/services/compute/virtual-machines/code/vm-22/vm-22.kql
  docs/content/services/compute/virtual-machines/code/vm-4/vm-4.kql
  docs/content/services/compute/virtual-machines/code/vm-5/vm-5.kql
  docs/content/services/compute/virtual-machines/code/vm-6/vm-6.kql
  docs/content/services/compute/virtual-machines/code/vm-7/vm-7.kql
  docs/content/services/compute/virtual-machines/code/vm-8/vm-8.kql
  docs/content/services/compute/virtual-machines/code/vm-9/vm-9.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#168 Fix the language highlight mode for the PowerShell code blocks for RT-1, RT-2
  docs/content/services/networking/route-table/_index.md
Labels: Bug

#173 Fix the category of NSG-3
  docs/content/services/networking/network-security-group/_index.md
Labels: Bug, Area: Service Guidance
