Repository Azure/Azure-Proactive-Resiliency-Library, pull requests merged in 2024-02, with the labels that each got.

#250 Adding Categories to all Recommendations of all Services
  docs/archetypes/service-bundle/_index.md
  docs/content/services/ai-ml/databricks/_index.md
  docs/content/services/compute/compute-gallery/_index.md
  docs/content/services/compute/image-templates/_index.md
  docs/content/services/compute/site-recovery/_index.md
  docs/content/services/compute/virtual-machine-scale-sets/_index.md
  docs/content/services/compute/virtual-machines/_index.md
  docs/content/services/container/aks/_index.md
  docs/content/services/container/container-registry/_index.md
  docs/content/services/database/cosmosdb/_index.md
  docs/content/services/database/sqldb/_index.md
  docs/content/services/integration/api-management/_index.md
  docs/content/services/iot/iot-hub/_index.md
  docs/content/services/management/management-group/_index.md
  docs/content/services/monitoring/log-analytics/_index.md
  docs/content/services/monitoring/resource-health-alerts/_index.md
  docs/content/services/networking/application-gateway/_index.md
  docs/content/services/networking/expressroute-circuits/_index.md
  docs/content/services/networking/expressroute-gateway/_index.md
  docs/content/services/networking/firewall/_index.md
  docs/content/services/networking/firewall/code/afw-1/afw-1.kql.fix
  docs/content/services/networking/firewall/code/afw-3/afw-3.kql.fix
  docs/content/services/networking/firewall/code/afw-5/afw-5.kql
  docs/content/services/networking/firewall/code/afw-5/afw-5.kql.fix
  docs/content/services/networking/firewall/code/afw-6/afw-6.kql
  docs/content/services/networking/firewall/code/afw-7/afw-7.kql
  docs/content/services/networking/front-door/_index.md
  docs/content/services/networking/front-door/code/afd-11/afd-11.kql.fix
  docs/content/services/networking/front-door/code/afd-16/afd-16.kql
  docs/content/services/networking/front-door/code/afd-17/afd-17.kql
  docs/content/services/networking/general-networking/_index.md
  docs/content/services/networking/general-networking/code/gnw-1/gnw-1.kql
  docs/content/services/networking/general-networking/code/gnw-2/gnw-2.kql
  docs/content/services/networking/general-networking/code/gnw-3/gnw-3.kql
  docs/content/services/networking/general-networking/code/gnw-4/gnw-4.kql
  docs/content/services/networking/general-networking/code/gnw-5/gnw-5.kql
  docs/content/services/networking/load-balancer/_index.md
  docs/content/services/networking/public-ip/_index.md
  docs/content/services/networking/traffic-manager/_index.md
  docs/content/services/networking/virtual-networks/_index.md
  docs/content/services/networking/vpn-gateway/_index.md
  docs/content/services/networking/web-application-firewall/_index.md
  docs/content/services/security/key-vault/_index.md
  docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
  docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
  docs/content/services/storage/azure-netapp-files/_index.md
  docs/content/services/storage/storage-Account/_index.md
  docs/content/services/storage/storage-Account/code/st-1/st-1.kql
  docs/content/services/storage/storage-Account/code/st-1/st-1.kql.fix
  docs/content/services/web/app-service-plan/_index.md
  docs/content/services/web/web-app/_index.md
Labels: Bug

#253 Add recommendation EVHNS-2
  docs/content/services/integration/event-hub/_index.md
  docs/content/services/integration/event-hub/code/evhns-2/evhns-2.kql
Labels: Area: Service Guidance

#216 fixed vnet-3 query
  docs/content/services/networking/virtual-networks/_index.md
  docs/content/services/networking/virtual-networks/code/vnet-3/vnet-3.kql
  docs/content/services/networking/virtual-networks/code/vnet-3/vnet-3.kql.fix
Labels: Bug, Area: Resource Graph Query(s)

#257 Vnet 1 fix
  docs/content/services/networking/virtual-networks/_index.md
  docs/content/services/networking/virtual-networks/code/vnet-1/vnet-1.kql
Labels: Bug, Area: Resource Graph Query(s)

#265 Updated category spelling errors
  docs/content/services/container/aks/_index.md
Labels: Bug

#247 Added "Specialized Workload" - HPC contents to APRL AB#31655
  docs/content/services/specialized-workloads/azure-hpc/_index.md
  docs/content/services/specialized-workloads/azure-hpc/code/hpc-1/hpc-1.kql
  docs/content/services/specialized-workloads/azure-hpc/code/hpc-2/hpc-2.kql
  docs/content/services/specialized-workloads/azure-hpc/code/hpc-3/hpc-3.kql
  docs/content/services/specialized-workloads/azure-hpc/code/hpc-4/hpc-4.kql
  docs/content/services/specialized-workloads/azure-hpc/code/hpc-5/hpc-5.kql
  docs/content/services/specialized-workloads/azure-hpc/code/hpc-6/hpc-6.kql
Labels: Area: Service Guidance, Enhancement, Area: Resource Graph Query(s), auto-merge :heavy_check_mark:

#264 add category guidance to contribution guide
  docs/content/contributing/_index.md
Labels: Enhancement, auto-merge :heavy_check_mark:

#266 add cr-6 recommendation
  docs/content/services/container/container-registry/_index.md
  docs/content/services/container/container-registry/code/cr-6/cr-6.kql
  docs/content/services/container/container-registry/code/cr-6/cr-6.kql.fix
Labels: Bug, Area: Resource Graph Query(s), auto-merge :heavy_check_mark:

#233 afw - Resource graph query fixes
  docs/content/services/networking/firewall/_index.md
  docs/content/services/networking/firewall/code/afw-1/afw-1.kql
  docs/content/services/networking/firewall/code/afw-1/afw-1.kql.fix
  docs/content/services/networking/firewall/code/afw-2/afw-2.kql
  docs/content/services/networking/firewall/code/afw-3/afw-3.kql
  docs/content/services/networking/firewall/code/afw-3/afw-3.kql.fix
Labels: Bug, Area: Resource Graph Query(s), auto-merge :heavy_check_mark:

#254 Add tags to sqldb queries
  docs/content/services/database/sqldb/code/sqldb-1/sqldb-1.kql
  docs/content/services/database/sqldb/code/sqldb-2/sqldb-2.kql
  docs/content/services/database/sqldb/code/sqldb-3/sqldb-3.kql
  docs/content/services/database/sqldb/code/sqldb-5/sqldb-5.kql
Labels: Enhancement, Area: Resource Graph Query(s), auto-merge :heavy_check_mark:

#255 Add tags to event hub queries
  docs/content/services/integration/event-hub/code/evhns-1/evhns-1.kql
Labels: Enhancement, Area: Resource Graph Query(s), auto-merge :heavy_check_mark:

#260 add tags to MG, backups, app insights
  docs/content/services/management/management-group/code/mg-1/mg-1.kql
  docs/content/services/migration/azure-backup/code/bk-1/bk-1.kql
  docs/content/services/monitoring/application-insights/code/appi-1/appi-1.kql
Labels: Enhancement, Area: Resource Graph Query(s), auto-merge :heavy_check_mark:

#267 add cr-7
  docs/content/services/container/container-registry/code/cr-7/cr-7.kql
  docs/content/services/container/container-registry/code/cr-7/cr-7.kql.fix
Labels: Bug, Area: Resource Graph Query(s), auto-merge :heavy_check_mark:

#280 Closes #279 (Metadata for Powershell scripts indicates sql instead of powershell like all other Powershell scripts)
  docs/content/services/integration/event-grid/_index.md
Labels: Bug

#277 modify recommendationid from "asp-5" to "app-5"
  docs/content/services/web/web-app/code/app-5/app-5.kql
Labels: Bug, Area: Hugo

#270 Feature: Added privacy page
  docs/content/privacy/_index.md
Labels: Enhancement, auto-merge :heavy_check_mark:

#273 Rosanto Quality updates for VMs, Netapp, Batch Accounts, AVS
  docs/content/Privacy/_index.md
  docs/content/privacy/_index.md
  docs/content/services/batch/_index.md
  docs/content/services/batch/batch-accounts/_index.md
  docs/content/services/batch/batch-accounts/code/ba-1/ba-1.kql
  docs/content/services/batch/batch-accounts/code/ba-2/ba-2.kql
  docs/content/services/batch/batch-accounts/code/ba-3/ba-3.kql
  docs/content/services/batch/batch-accounts/code/ba-4/ba-4.kql
  docs/content/services/batch/batch-accounts/code/ba-5/ba-5.kql
  docs/content/services/batch/batch-accounts/code/ba-6/ba-6.kql
  docs/content/services/compute/virtual-machines/_index.md
  docs/content/services/compute/virtual-machines/code/vm-23/vm-23.kql
  docs/content/services/compute/virtual-machines/code/vm-24/vm-24.kql
  docs/content/services/compute/virtual-machines/code/vm-25/vm-25.kql
  docs/content/services/compute/virtual-machines/code/vm-26/vm-26.kql
  docs/content/services/specialized-workloads/azure-hpc/_index.md
  docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
  docs/content/services/storage/azure-netapp-files/_index.md
  services-abbreviations.csv
Labels: Bug, Area: Service Guidance, Area: Resource Graph Query(s)

#275 Added Service Bus namespace Availability Zones recommendation
  docs/content/services/integration/service-bus/_index.md
  docs/content/services/integration/service-bus/code/sbns-1/sbns-1.kql
Labels: Area: Service Guidance, Enhancement, Area: Resource Graph Query(s)

#271 New azure backup RSV cross region restore recommendation
  docs/content/services/migration/azure-backup/_index.md
  docs/content/services/migration/azure-backup/code/bk-2/bk-2.kql
Labels: Area: Service Guidance, Enhancement, Area: Resource Graph Query(s)

#269 ioth fixes
  docs/content/services/iot/iot-hub/_index.md
  docs/content/services/iot/iot-hub/code/ioth-2/ioth-2.kql
  docs/content/services/iot/iot-hub/code/ioth-2/ioth-2.kql.fix
  docs/content/services/iot/iot-hub/code/ioth-4/ioth-4.kql
  docs/content/services/iot/iot-hub/code/ioth-4/ioth-4.kql.fix
  docs/content/services/iot/iot-hub/code/ioth-6/ioth-6.kql
  docs/content/services/iot/iot-hub/code/ioth-6/ioth-6.kql.fix
Labels: Bug, Area: Resource Graph Query(s), auto-merge :heavy_check_mark:

#282 Update Storage _index.md for the table: ST1 Script available.
  docs/content/services/storage/storage-Account/_index.md
Labels: Bug, Area: Service Guidance, Area: Resource Graph Query(s)

#284 Update ANF minor changes
  docs/content/services/storage/azure-netapp-files/_index.md
  services-abbreviations.csv
Labels: Area: Service Guidance

#286 VM-24 KQL initial
  docs/content/services/compute/virtual-machines/code/vm-24/vm-24.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#281 Lowering weight of privacy page
  docs/content/Privacy/_index.md
Labels: Area: Hugo, auto-merge :heavy_check_mark:

#295 add db for postgresql recommendation
  docs/content/services/database/db-for-postgresql/_index.md
  docs/content/services/database/db-for-postgresql/code/psql-1/psql-1.azcli
  docs/content/services/database/db-for-postgresql/code/psql-1/psql-1.ps1
  docs/content/services/database/db-for-postgresql/code/psql-2/psql-2.kql
Labels: Area: Service Guidance

#294 Add DB for MySQL recommendations
  docs/content/services/database/db-for-mysql/_index.md
  docs/content/services/database/db-for-mysql/code/mysql-1/mysql-1.kql
  docs/content/services/database/db-for-mysql/code/mysql-2/mysql-2.kql
  services-abbreviations.csv
Labels: Area: Service Guidance

#289 agw-9 Ensure Application Gateway Subnet is using a /24 subnet mask
  docs/content/services/networking/application-gateway/code/agw-9/agw-9.kql
Labels: Area: Resource Graph Query(s)

#296 Updated AVS-1, AVS-2, AVS-3, added AVS-4, AVS-5, AVS-6, AVS-7
  docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
  docs/content/services/specialized-workloads/azure-vmware-solution/avs-1.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-4/avs-4.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-5/avs-5.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-6/avs-6.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-7/avs-7.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-8/avs-8.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-9/avs-9.kql
Labels: Area: Service Guidance, Enhancement, Area: Resource Graph Query(s)

#290 kv-3 - Enable Azure Private Link Service for Key vault
  docs/content/services/security/key-vault/code/kv-3/kv-3.kql
Labels: Area: Resource Graph Query(s)

#299 avs kql updates
  docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
  docs/content/services/specialized-workloads/azure-vmware-solution/avs-1.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-3/avs-3.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-4/avs-4.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-5/avs-5.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-6/avs-6.kql
Labels: Area: Service Guidance, Area: Resource Graph Query(s)
