Repository Azure/Azure-Proactive-Resiliency-Library, pull requests merged in 2024-01, with the labels that each got.

#162 Updated KQL for VMSS Recommendations
  docs/content/services/compute/virtual-machine-scale-sets/_index.md
  docs/content/services/compute/virtual-machine-scale-sets/code/vmss-2/vmss-2.kql
  docs/content/services/compute/virtual-machine-scale-sets/code/vmss-3/vmss-3.kql
  docs/content/services/compute/virtual-machine-scale-sets/code/vmss-4/vmss-4.kql
  docs/content/services/compute/virtual-machine-scale-sets/code/vmss-9/vmss-9.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#182 Fix duplicated code blocks for ASP
  docs/content/services/web/app-service-plan/_index.md
Labels: Bug

#180 Add params to VM-16
  docs/content/services/compute/virtual-machines/code/vm-16/vm-16.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#166 Fix acronyms
  docs/content/services/networking/expressroute-gateway/_index.md
  docs/content/services/networking/expressroute-gateway/code/ergw-1/ergw-1.kql
  docs/content/services/networking/expressroute-gateway/code/ergw-2/ergw-2.kql
  docs/content/services/networking/expressroute-gateway/code/ergw-3/ergw-3.kql
  docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.kql
  docs/content/services/networking/general-networking/_index.md
  docs/content/services/networking/general-networking/code/gnw-1/gnw-1.kql
  docs/content/services/networking/general-networking/code/gnw-2/gnw-2.kql
  docs/content/services/networking/general-networking/code/gnw-3/gnw-3.kql
  docs/content/services/networking/general-networking/code/gnw-4/gnw-4.kql
  docs/content/services/networking/general-networking/code/gnw-5/gnw-5.kql
  services-abbreviations.csv
Labels: Bug, Area: Service Guidance

#188 Add NSG-4 query
  docs/content/services/networking/network-security-group/_index.md
  docs/content/services/networking/network-security-group/code/nsg-4/nsg-4.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#181 Add param to VM-17
  docs/content/services/compute/virtual-machines/code/vm-17/vm-17.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#174 Fix the recommendation title in summary table of NSG
  docs/content/services/networking/network-security-group/_index.md
Labels: Bug, Area: Service Guidance

#184 Fix VM-10
  docs/content/services/compute/virtual-machines/code/vm-10/vm-10.kql
Labels: Bug, Area: Resource Graph Query(s)

#151 Guidance and KQL query for asr-2 (Test Failover)
  docs/content/services/compute/site-recovery/_index.md
  docs/content/services/compute/site-recovery/code/asr-2/asr-2.kql
Labels: Enhancement, Needs: Attention :wave:

#190 Add VM-21 ARG query
  docs/content/services/compute/virtual-machines/_index.md
  docs/content/services/compute/virtual-machines/code/vm-21/vm-21.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#163 Updating ANF Recommendations as per Feedback from NetApp Team
  docs/content/services/storage/azure-netapp-files/_index.md
  docs/content/services/storage/azure-netapp-files/code/anf-1/anf-1.kql
  docs/content/services/storage/azure-netapp-files/code/anf-2/anf-2.kql
  docs/content/services/storage/azure-netapp-files/code/anf-3/anf-3.kql
  docs/content/services/storage/azure-netapp-files/code/anf-4/anf-4.kql
  docs/content/services/storage/azure-netapp-files/code/anf-5/anf-5.kql
  docs/content/services/storage/azure-netapp-files/code/anf-6/anf-6.kql
Labels: Bug, Area: Service Guidance, Area: Resource Graph Query(s)

#198 Improve VM-18 query
  docs/content/services/compute/virtual-machines/code/vm-18/vm-18.kql
Labels: Bug, Area: Resource Graph Query(s)

#185 Add NSG-1 as PowerShell script
  docs/content/services/networking/network-security-group/_index.md
  docs/content/services/networking/network-security-group/code/nsg-1/nsg-1.ps1
Labels: Enhancement

#187 Add NSG-3 as PowerShell script
  docs/content/services/networking/network-security-group/_index.md
  docs/content/services/networking/network-security-group/code/nsg-3/nsg-3.ps1
Labels: Enhancement

#156 Ys2 avd
  docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
  docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-1/avd-1.kql
  docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-2/avd-2.kql
  docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-3/avd-3.kql
Labels: Area: Service Guidance, Enhancement, Area: Resource Graph Query(s)

#191 Adding tags to VMSS Queries in APRL
  docs/content/services/compute/virtual-machine-scale-sets/code/vmss-1/vmss-1.kql
  docs/content/services/compute/virtual-machine-scale-sets/code/vmss-4/vmss-4.kql
  docs/content/services/compute/virtual-machine-scale-sets/code/vmss-5/vmss-5.kql
  docs/content/services/compute/virtual-machine-scale-sets/code/vmss-7/vmss-7.kql
  docs/content/services/compute/virtual-machine-scale-sets/code/vmss-8/vmss-8.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#205 Remove nsg-4.kql.fix file
  docs/content/services/networking/network-security-group/code/nsg-4/nsg-4.kql.fix
Labels: Bug

#200 Ys3 iteration2 AVD updates
  docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
  docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-4/avd-4.kql
  docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-5/avd-5.kql
  docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-6/avd-6.kql
Labels: Area: Service Guidance, Enhancement

#203 Agw-1 wording adjustment
  docs/content/services/networking/application-gateway/_index.md
Labels: Area: Service Guidance, Enhancement

#204 Change the recommendation title wording of diagnostics settings
  docs/content/services/compute/virtual-machines/_index.md
  docs/content/services/container/container-registry/_index.md
  docs/content/services/integration/event-grid/_index.md
  docs/content/services/networking/network-security-group/_index.md
  docs/content/services/storage/storage-Account/_index.md
Labels: Area: Service Guidance, Enhancement

#193 Adding KQL for App Service And App Service Plans
  docs/content/services/web/app-service-plan/_index.md
  docs/content/services/web/app-service-plan/code/asp-1/asp-1.kql
  docs/content/services/web/app-service-plan/code/asp-1/asp-1.kql.fix
  docs/content/services/web/app-service-plan/code/asp-2/asp-2.kql
  docs/content/services/web/app-service-plan/code/asp-2/asp-2.kql.fix
  docs/content/services/web/app-service-plan/code/asp-3/asp-3.kql
  docs/content/services/web/app-service-plan/code/asp-4/asp-4.kql
  docs/content/services/web/app-service-plan/code/asp-5/asp-5.kql
  docs/content/services/web/app-service-plan/code/asp-5/asp-5.kql.fix
  docs/content/services/web/web-app/_index.md
  docs/content/services/web/web-app/code/app-1/app-1.kql
  docs/content/services/web/web-app/code/app-2/app-2.kql
  docs/content/services/web/web-app/code/app-2/app-2.kql.fix
  docs/content/services/web/web-app/code/app-3/app-3.kql
  docs/content/services/web/web-app/code/app-4/app-4.kql
  docs/content/services/web/web-app/code/app-5/app-5.kql
  docs/content/services/web/web-app/code/app-5/app-5.kql.fix
  docs/content/services/web/web-app/code/app-6/app-6.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#172 Update AKS Guidance
  docs/content/services/container/aks/_index.md
  docs/content/services/container/aks/code/aks-10/aks-10.kql
  docs/content/services/container/aks/code/aks-11/aks-11.kql
  docs/content/services/container/aks/code/aks-12/aks-12.kql
  docs/content/services/container/aks/code/aks-13/aks-13.kql
  docs/content/services/container/aks/code/aks-14/aks-14.kql
  docs/content/services/container/aks/code/aks-15/aks-15.kql
  docs/content/services/container/aks/code/aks-16/aks-16.kql
  docs/content/services/container/aks/code/aks-17/aks-17.kql
  docs/content/services/container/aks/code/aks-18/aks-18.kql
  docs/content/services/container/aks/code/aks-19/aks-19.kql
  docs/content/services/container/aks/code/aks-20/aks-20.kql
  docs/content/services/container/aks/code/aks-21/aks-21.kql
  docs/content/services/container/aks/code/aks-22/aks-22.kql
  docs/content/services/container/aks/code/aks-23/aks-23.kql
  docs/content/services/container/aks/code/aks-24/aks-24.kql
  docs/content/services/container/aks/code/aks-25/aks-25.kql
  docs/content/services/container/aks/code/aks-26/aks-26.kql
  docs/content/services/container/aks/code/aks-8/aks-8.kql
  docs/content/services/container/aks/code/aks-9/aks-9.kql
Labels: Area: Service Guidance, Enhancement, Area: Resource Graph Query(s), Needs: Attention :wave:

#206 Adding tags to AKS Queries in APRL
  docs/content/services/container/aks/code/aks-1/aks-1.kql
  docs/content/services/container/aks/code/aks-2/aks-2.kql
  docs/content/services/container/aks/code/aks-3/aks-3.kql
  docs/content/services/container/aks/code/aks-4/aks-4.kql
  docs/content/services/container/aks/code/aks-5/aks-5.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#153 fixed query for vm-13
  docs/content/services/compute/virtual-machines/_index.md
  docs/content/services/compute/virtual-machines/code/vm-13/vm-13.kql
  docs/content/services/compute/virtual-machines/code/vm-13/vm-13.kql.fix
Labels: Bug, Area: Resource Graph Query(s)

#207 Ys4 interation3 avd updates
  docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
  docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-7/avd-7.kql
  docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-8/avd-8.kql
Labels: Area: Service Guidance, Enhancement

#152 Query Resource Health Alerts
  docs/content/services/monitoring/resource-health-alerts/_index.md
  docs/content/services/monitoring/resource-health-alerts/code/msr-1.kql
Labels: Area: Service Guidance, Enhancement, Area: Resource Graph Query(s)

#214 Clarifies wording for ERC-2
  docs/content/services/networking/expressroute-circuits/_index.md
Labels: Area: Service Guidance

#217 Add Tags to Container Registries ARG Queries in APRL
  docs/content/services/container/container-registry/code/cr-1/cr-1.kql
  docs/content/services/container/container-registry/code/cr-12/cr-12.kql
  docs/content/services/container/container-registry/code/cr-2/cr-2.kql
  docs/content/services/container/container-registry/code/cr-3/cr-3.kql
  docs/content/services/container/container-registry/code/cr-6/cr-6.kql.fix
  docs/content/services/container/container-registry/code/cr-7/cr-7.kql.fix
  docs/content/services/container/container-registry/code/cr-8/cr-8.kql
  docs/content/services/container/container-registry/code/cr-9/cr-9.kql.fix
Labels: Area: Resource Graph Query(s)

#212 Initial commit for Azure VMware Solution.
  docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-1/avs-1.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-2/avs-2.kql
  docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-3/avs-3.kql
Labels: Area: Service Guidance, Enhancement

#218 Added new guidance ERGW-4
  docs/content/services/networking/expressroute-gateway/_index.md
  docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.kql
Labels: Area: Service Guidance

#223 (fix) add missing aks to service list
  services-abbreviations.csv
Labels: Bug

#228 Add networking team responsibility to PRs
  CODEOWNERS
Labels: Enhancement

#224 Add automation standards for PowerShell scripts
  docs/content/contributing/_index.md
Labels: Enhancement

#225 Rewrite and re-order APRL ERC guidance to align with Jan 2024 ER resiliency efforts
  docs/content/services/networking/expressroute-circuits/_index.md
  docs/content/services/networking/expressroute-circuits/code/erc-1/erc-1.kql
  docs/content/services/networking/expressroute-circuits/code/erc-3/erc-3.kql
  docs/content/services/networking/expressroute-circuits/code/erc-7/erc-7.kql
  docs/content/services/networking/expressroute-circuits/code/erc-8/erc-8.kql
  docs/content/services/networking/expressroute-circuits/code/erc-9/erc-9.kql
Labels: Area: Service Guidance, Area: Resource Graph Query(s)

#229 fixed it-2
  docs/content/services/compute/image-templates/_index.md
  docs/content/services/compute/image-templates/code/it-2/it-2.kql
  docs/content/services/compute/image-templates/code/it-2/it-2.kql.fix
Labels: Bug, Area: Resource Graph Query(s)

#227 Add Tags to Cosmos DB ARG Queries in APRL
  docs/content/services/database/cosmosdb/code/cosmos-1/cosmos-1.kql
  docs/content/services/database/cosmosdb/code/cosmos-3/cosmos-3.kql
  docs/content/services/database/cosmosdb/code/cosmos-5/cosmos-5.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#230 Added AVD recommendation 9
  docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
  docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-9/avd-9.kql
Labels: Area: Service Guidance, Enhancement, Area: Resource Graph Query(s)

#234 Fix PowerShell comment syntax in contribution guide
  docs/content/contributing/_index.md
Labels: Bug

#235 Add tags to Redis Cache ARG query
  docs/content/services/database/redis-cache/code/redis-1/redis-1.kql
Labels: Enhancement, Area: Resource Graph Query(s)

#244 Remove vm-11 broken query
  docs/content/services/compute/virtual-machines/_index.md
  docs/content/services/compute/virtual-machines/code/vm-11/vm-11.kql
Labels: Bug, Area: Resource Graph Query(s)

#243 AKS guidance revisions
  docs/content/services/container/aks/_index.md
  docs/content/services/container/aks/code/aks-1/aks-1.kql
  docs/content/services/container/aks/code/aks-10/aks-10.kql
  docs/content/services/container/aks/code/aks-12/aks-12.kql
  docs/content/services/container/aks/code/aks-13/aks-13.kql
  docs/content/services/container/aks/code/aks-16/aks-16.kql
  docs/content/services/container/aks/code/aks-17/aks-17.kql
  docs/content/services/container/aks/code/aks-19/aks-19.kql
  docs/content/services/container/aks/code/aks-2/aks-2.kql
  docs/content/services/container/aks/code/aks-20/aks-20.kql
  docs/content/services/container/aks/code/aks-21/aks-21.kql
  docs/content/services/container/aks/code/aks-22/aks-22.kql
  docs/content/services/container/aks/code/aks-23/aks-23.kql
  docs/content/services/container/aks/code/aks-24/aks-24.kql
  docs/content/services/container/aks/code/aks-25/aks-25.kql
  docs/content/services/container/aks/code/aks-26/aks-26.kql
  docs/content/services/container/aks/code/aks-6/aks-6.kql
  docs/content/services/container/aks/code/aks-7/aks-7.kql
Labels: Bug, Area: Service Guidance, Needs: Author Feedback
